### PR TITLE
Add Power operator to math variables

### PR DESCRIPTION
**Pull request by DeputyLOL**
Allows for squaring and rooting.

This is the first time i've done something like this so you may want to double check it.

### CODE REVIEW

**Comment by MOARdV** [comment]
Looks good.

**Comment by MOARdV** [comment]
And let's try actually merging the pull request instead of closing it...  Need more coffee.

**Comment by DeputyLOL** [comment]
Always need more coffee :D

**Comment by DeputyLOL** [comment]
I wanted to test it out but I'm not smart enough t figure out how to do that. Do you think you could add it to a dev build?

**Comment by MOARdV** [comment]
> I wanted to test it out but I'm not smart enough t figure out how to do that. Do you think you could add it to a dev build?

I'll try to get one out later today.

**Comment by DeputyLOL** [comment]
Thank you

**Comment by MOARdV** [comment]
Got a little crazy at work, so I didn't get to this at lunch.  [Here you go](https://www.dropbox.com/s/t3xx8whfwg4bwkx/RasterPropMonitor-dev.0.24.x.zip?dl=0).

**Comment by DeputyLOL** [comment]
Thank you. There is problems with my internet at the moment so I won't be able to download it right now. Thank you anyway, I'll let you know when I download it.

**Comment by DeputyLOL** [comment]
Downloaded. It works perfectly! Thank you!!!

**Pull request merged**
