### PR TITLE
Added variable for number of experiments stored onboard.

### PR DESCRIPTION
**Pull request by Tahvohck**
Just a simple variable I wanted. I didn't compile and test this, but honestly if I messed up a simple +=1 and switch statement, I should probably go cry in a corner for a bit.

Which means I probably messed something up somewhere.

### CODE REVIEW

**Comment by MOARdV** [comment]
Well, the formatting on the += 1 is a bit off...  (kidding)

This will need to wait until my big merge gets pulled in (later today), and you'll need to resolve the diffs with your branch, but I'll include it in the upcoming release.

**Comment by Tahvohck** [comment]
No problem. I'll keep an eye out for it.

**Comment by MOARdV** [comment]
It looks like you won't need to merge anything.  Incorporating for v0.21.0

**Comment by Tahvohck** [comment]
Good to hear. Didn't think it'd cause any conflicts.

**Pull request merged**
