### PR TITLE
Add more operators to math variables

### PR DESCRIPTION
**Pull request by DeputyLOL**
Added angle delta which gives the difference between angles.
Also added Atan2 with gives you the angle between 2 coordinates.
Let me know what you think!

### CODE REVIEW

**Comment by DeputyLOL** [comment]
Do you think you could add this to a dev build please?

**Comment by MOARdV** [comment]
I'll have to fix this before it will compile - DeltaAngle is part of Unity's Mathf, not C# Math.

**Comment by DeputyLOL** [comment]
Do you think you could add a math variable that calculates the difference of 2 angles?

**Comment by DeputyLOL** [comment]
Also I have a feeling that the output would be in radians. Do you think we could have another function that converts it to degrees? Something like the 'meterstofeet'.
Maybe even have something that does it automatically?

**Pull request merged**
